//this is sample dummy data for first sprint
//this data is more refined and catered for our app compared to dummydb.js

//user array to be refactored with new table schema. 


export const user = [
    {
        "user_id": "1",
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": "2",
        "fullname": "Ervin Howell",
        "nickname": "Erv",
        "email" : "Ervinge@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "078 4091 2790 ",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "24 West Street",
        "address_city" : "Liverpool",
        "address_postcode" : "L7 6LJ",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": "3",
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": "4",
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": "5",
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": "6",
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
    ]

  export const petService = [
    {
      "service_id" : "1",
	    "sitter_id" : "2",
      "tagline" : "I am a pet owner!",
      "summary" : "'I love all animals and want to take care of them all!",
      "pet_type" : "Dog",
      "service_type" : "walking",
      "price" : "15",
      "published_at" : "timestamp",
      "created_at " : "timestamp",
      "updated_at " : "timestamp",
      "how_many_pets" :"5",
      "pet_size" : "big"
    },
    {
      "service_id" : "2",
	    "sitter_id" : "2",
      "tagline" : "I am a pet owner!",
      "summary" : "'I love all animals and want to take care of them all!",
      "pet_type" : "Dog",
      "service_type" : "house sitting",
      "price" : "15",
      "published_at" : "timestamp",
      "created_at " : "timestamp",
      "updated_at " : "timestamp",
      "how_many_pets" :"5",
      "pet_size" : "big"
    },
    {
      "service_id" : "3",
	    "sitter_id" : "3",
      "tagline" : "I am a pet owner!",
      "summary" : "'I love all animals and want to take care of them all!",
      "pet_type" : "Cat",
      "service_type" : "house sitting",
      "price" : "15",
      "published_at" : "timestamp",
      "created_at " : "timestamp",
      "updated_at " : "timestamp",
      "how_many_pets" :"5",
      "pet_size" : "big"
    },
    {
      "service_id" : "4",
	    "sitter_id" : "3",
      "tagline" : "I am a pet owner!",
      "summary" : "'I love all animals and want to take care of them all!",
      "pet_type" : "Dog",
      "service_type" : "walking",
      "price" : "15",
      "published_at" : "timestamp",
      "created_at " : "timestamp",
      "updated_at " : "timestamp",
      "how_many_pets" :"5",
      "pet_size" : "big"
    },
    {
      "service_id" : "5",
	    "sitter_id" : "3",
      "tagline" : "I am a pet owner!",
      "summary" : "'I love all animals and want to take care of them all!",
      "pet_type" : "Dog",
      "service_type" : "walking",
      "price" : "15",
      "published_at" : "timestamp",
      "created_at " : "timestamp",
      "updated_at " : "timestamp",
      "how_many_pets" :"5",
      "pet_size" : "big"
    },
    {
      "service_id" : "4",
	    "sitter_id" : "3",
      "tagline" : "I am a pet owner!",
      "summary" : "'I love all animals and want to take care of them all!",
      "pet_type" : "Dog",
      "service_type" : "walking",
      "price" : "15",
      "published_at" : "timestamp",
      "created_at " : "timestamp",
      "updated_at " : "timestamp",
      "how_many_pets" :"5",
      "pet_size" : "big"
    },
   
  ]