//this is sample dummy data for first sprint
//this data is more refined and catered for our app compared to dummydb.js

//user array to be refactored with new table schema. 


export const user = [
    {
        "user_id": 1,
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": 2,
        "fullname": "Ervin Howell",
        "nickname": "Erv",
        "email" : "Ervinge@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "078 4091 2790 ",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "24 West Street",
        "address_city" : "Liverpool",
        "address_postcode" : "L7 6LJ",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": 1,
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": 1,
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": 1,
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
      {
        "user_id": 1,
        "fullname": "Leanne Graham",
        "nickname": "Lea",
        "email" : "Sincere@april.biz",
        "created_at" : "timestamp",
        "updated_at" : "timestamp",
        "phone_number" : "070 2562 2287",
        "profile_image" : "https://img.freepik.com/free-photo/pleasant-looking-serious-man-stands-profile-has-confident-expression-wears-casual-white-t-shirt_273609-16959.jpg?w=2000",
        "address_street": "6 King Street",
        "address_city" : "BLACKBURN",
        "address_postcode" : "BB62 6VD",
        "latitude" : "0.00",
        "longitude" : "0.00",
      },
    ]